"""Export / load a small demo slice — `scripts/seed_demo.py --export|--load`.

A deployment does not need 1.09M bars. It needs the 30 instruments on the demo
watchlist, the index series attribution reads, and the events already detected
for them: roughly 14k bars instead of a million, which is the difference
between a container that boots in seconds and one that times out.

The export is committed as gzipped SQL so a fresh environment is reproducible
from the repository alone, with no credentials and no network. `--load` is
idempotent and refuses to touch a database that already has bars, so a redeploy
never clobbers live data.
"""
from __future__ import annotations

import argparse
import gzip
import json
import os
import sys
from pathlib import Path

import psycopg

REPO_ROOT = Path(__file__).resolve().parents[1]
SEED_PATH = REPO_ROOT / "data" / "demo_seed.sql.gz"
DEFAULT_DATABASE_URL = "postgresql://signal:signal@localhost:5433/signal"
DEMO_USER_ID = "00000000-0000-4000-8000-000000000001"

# Only the market factor and the sectors the demo instruments actually belong
# to. The full index table is 69,992 rows and attribution reads a handful.
_WL = ("SELECT isin FROM watchlist_item WHERE user_id = %(uid)s")

TABLES = [
    ("sector", "SELECT * FROM sector", {}),
    # Every instrument, not just the watchlisted ones. Bars stay restricted to
    # the demo 30, but symbol resolution must work for anything a visitor
    # types: exporting only the watchlist makes "add TCS" answer
    # "Unknown symbol: TCS", which reads as a broken product rather than as
    # a deliberately small dataset. ~3k narrow rows.
    ("instrument", "SELECT * FROM instrument", {}),
    ("bar",
     "SELECT * FROM bar WHERE isin IN (SELECT isin FROM watchlist_item "
     "WHERE user_id = %(uid)s)", {}),
    ("index_bar",
     "SELECT * FROM index_bar WHERE index_name = 'Nifty 50' OR index_name IN ("
     "  SELECT s.index_symbol FROM sector s WHERE s.index_symbol IS NOT NULL)", {}),
    ("corp_action",
     "SELECT * FROM corp_action WHERE isin IN (SELECT isin FROM watchlist_item "
     "WHERE user_id = %(uid)s)", {}),
    ("event",
     "SELECT * FROM event WHERE isin IN (SELECT isin FROM watchlist_item "
     "WHERE user_id = %(uid)s)", {}),
]


def _literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return repr(v)
    # psycopg hands JSONB back as a dict. `str(dict)` is Python repr, which
    # uses single quotes and is not JSON — Postgres rejects it on reload with
    # "invalid input syntax for type json". Serialise properly, sorted so the
    # export is byte-stable across runs.
    if isinstance(v, (dict, list)):
        s = json.dumps(v, sort_keys=True, default=str).replace("'", "''")
        return f"'{s}'"
    s = str(v).replace("'", "''")
    return f"'{s}'"


def export(conn, out: Path) -> int:
    rows_written = 0
    parts: list[str] = [
        "-- AUTO-GENERATED by scripts/seed_demo.py --export. Do not hand-edit.",
        "BEGIN;",
    ]
    with conn.cursor() as cur:
        for table, sql, _ in TABLES:
            cur.execute(sql, {"uid": DEMO_USER_ID})
            cols = [d.name for d in cur.description]
            rows = cur.fetchall()
            if not rows:
                continue
            collist = ", ".join(cols)
            for r in rows:
                vals = ", ".join(_literal(v) for v in r)
                parts.append(
                    f"INSERT INTO {table} ({collist}) VALUES ({vals}) "
                    "ON CONFLICT DO NOTHING;")
            rows_written += len(rows)
            parts.append(f"-- {table}: {len(rows)} rows")
    # event_id is BIGSERIAL and the rows above carry explicit ids; without this
    # the next insert collides with a seeded id.
    parts.append(
        "SELECT setval('event_event_id_seq', "
        "COALESCE((SELECT max(event_id) FROM event), 1));")
    parts.append("COMMIT;")
    out.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(out, "wt", encoding="utf-8") as fh:
        fh.write("\n".join(parts) + "\n")
    return rows_written


def load(conn, src: Path) -> str:
    with conn.cursor() as cur:
        cur.execute("SELECT count(*) FROM bar")
        if cur.fetchone()[0]:
            return "skipped: bar already populated"
        sql = gzip.open(src, "rt", encoding="utf-8").read()
        cur.execute(sql)
    conn.commit()
    with conn.cursor() as cur:
        cur.execute("SELECT count(*) FROM bar")
        bars = cur.fetchone()[0]
    return f"loaded: {bars} bars"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="scripts/seed_demo.py")
    ap.add_argument("--export", action="store_true")
    ap.add_argument("--load", action="store_true")
    ap.add_argument("--path", default=str(SEED_PATH))
    ap.add_argument("--database-url",
                    default=os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL))
    args = ap.parse_args(argv)
    path = Path(args.path)

    with psycopg.connect(args.database_url) as conn:
        if args.export:
            n = export(conn, path)
            print(f"exported {n} rows -> {path} ({path.stat().st_size} bytes)")
        elif args.load:
            print(load(conn, path))
        else:
            ap.error("pass --export or --load")
    return 0


if __name__ == "__main__":
    sys.exit(main())
